### ISSUE TITLE
Your Pipfile.lock (d0d920) is out of date. Expected: (af5892).

### ISSUE THREAD

**Issue by roheez** [metabolize/rq-dashboard-on-heroku#16]
I'm getting the following error when trying to deploy on Heroku. Would love your help. Thank you! 

-----> Python app detected
cp: cannot stat '/tmp/build_3c7b961e397a690cc3aa7542b23a6212/requirements.txt': No such file or directory
-----> Installing python-3.7.7
-----> Installing pip
-----> Installing dependencies with Pipenv 2018.5.18…
       Your Pipfile.lock (d0d920) is out of date. Expected: (af5892).
       Aborting deploy.
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by joe-gordian-software** [comment]
created https://github.com/metabolize/rq-dashboard-on-heroku/pull/17
